name: Build and Deploy MERN Stack App to Docker Hub

on:
  push:
    branches:
      - main

env:
  MONGO_URI: ${{ secrets.MONGO_URI }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and Test Frontend
        working-directory: ./frontend
        run: |
          npm install

      - name: Install and Test Backend
        working-directory: ./backend
        run: |
          npm install

      - name: Build Frontend Docker Image
        working-directory: ./frontend
        run: |
          docker build -t ismailza/mern-stack-app-frontend:${{github.run_number}} -t ismailza/mern-stack-app-frontend:latest .

      - name: Build Backend Docker Image
        working-directory: ./backend
        run: |
          docker build -t ismailza/mern-stack-app-backend:${{github.run_number}} -t ismailza/mern-stack-app-backend:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Images to Docker Hub
        run: |
          docker push ismailza/mern-stack-app-frontend:${{github.run_number}}
          docker push ismailza/mern-stack-app-frontend:latest
          docker push ismailza/mern-stack-app-backend:${{github.run_number}}
          docker push ismailza/mern-stack-app-backend:latest
